### ISSUE TITLE
No darknet19.pb as our pre-trained model

### ISSUE THREAD

**Issue by JackFram** [JoshuaPiinRueyPan/ViolenceDetection#1]
Hi, I find that there is no darknet19.pb to train the network, where can I get it and thanks a lot!

**Comment by JoshuaPiinRueyPan** [comment]
Hi,
   Sorry, I forgot to add it to the _README.md_.  Thanks for point it out.  Now, you can follow the instruction in section: _Quick Start/Training/5._ in _README.md_.

**Comment by JackFram** [comment]
Really useful repo, thx
