### ISSUE TITLE
AttributeError: 'Main' object has no attribute 'session' in src/Trainer.py file, line 39

### ISSUE THREAD

**Issue by weirditya** [JoshuaPiinRueyPan/ViolenceDetection#40]
**Facing issue on both system and google colab, also the path is absolutely correct. And I am using the same library versions as mentioned in the repo**

Traceback (most recent call last):
  File "C:\Users\Aditya\Desktop\ActivityRecognition\ViolenceDetection\src\Trainer.py", line 39, in __del__
    self._dataManager.Stop()
AttributeError: 'Trainer' object has no attribute '_dataManager'
Exception ignored in: <bound method Main.__del__ of <__main__.Main object at 0x0000015DBF7F8400>>
Traceback (most recent call last):
  File "Train.py", line 52, in __del__
    self.session.close()
AttributeError: 'Main' object has no attribute 'session'

**Comment by maacofficial** [comment]
You should run Train_Val_Test_spliter.py file in `tools python tools/Train_Val_Test_spliter.py`
